name: Color Logger

on:
  push:
    branches: [ main ]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout git repo'
    - uses: actions/checkout@v3
    - name: 'Set up node'
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: 'Install Dependencies'
      run: npm install 
    - name: 'Test code ' 
      run: npm test 